---
language: elixir
elixir:
  - 1.7.3
otp_release:
  - 21.0
  - 20.3
  - 19.3

script:
  - if [ "$TRAVIS_ELIXIR_VERSION" = "1.7.3" ]; then mix format --check-formatted --dry-run; fi
  - MIX_ENV=test mix compile && mix test
  - if [ "$TRAVIS_ELIXIR_VERSION" = "1.7.3" ] && [ "$TRAVIS_OTP_RELEASE" = "21.0" ]; then mix dialyzer; fi

cache:
  directories:
    - .mix
    - _build
